#pragma once
#include <SFML/Audio.hpp>
#include <vector>
#include <unordered_map>
#include <string>
#include <cmath>
#include <random>

namespace bm {

class SoundManager {
public:
    SoundManager();
    void playDotBlip();
    void playGoldDisc();
    void playFootstep();
    void playCaptureBoss(int streak);
    void playCaughtByBoss();
    void playFishOrTreat();
    void playTpsDeliver();
    void playGameOver();
    void playLevelStart();
    void playTeleport();
    void playWaterGunPickup();
    void playWaterGunShoot();
    void playWaterGunSplash();
    void playMachine(const std::string& name);
    // Distinct sound for each traveler type when it arrives (idx 0..11, matching
    // the TRAVELERS / SpriteKit TravelerSound order). Mirrors playTravelerArrive.
    void playTravelerArrive(int soundIndex);
    // Plays a pre-rendered digitized voice clip from assets/voice/<key>.wav
    // (generated by scripts/generate_voices.sh). Missing files are silently
    // ignored so the game still runs without the clips.
    void playVoice(const std::string& key);
    // Plays a random clip from a numbered pool: assets/voice/<prefix>_1.wav,
    // <prefix>_2.wav, ... The pool size is probed once (cached), so the line
    // count can change in generate_voices.sh without touching the code.
    void playVoiceRandom(const std::string& prefix);
    void startBackgroundMusic(bool mib);
    void stopBackgroundMusic();
    void startGoldDiscBass(bool mib);
    void stopGoldDiscBass();
    void pauseAudio();
    void resumeAudio();

private:
    sf::SoundBuffer tone(float freq, float dur, float vol, float decay = 12.0f);
    sf::SoundBuffer sweep(float from, float to, float dur, float vol);
    sf::SoundBuffer sequence(const std::vector<float>& notes, float perNote, float vol);
    sf::SoundBuffer makeNoise(float dur, int bursts, float vol);
    // TPS machine sounds — direct ports of the SpriteKit synth* functions.
    sf::SoundBuffer synthPrinter();   // square-wave chirps + noise/hum whir tail
    sf::SoundBuffer synthFax();        // vibrato sine segments
    sf::SoundBuffer synthPageFlip();   // cover sheet: high-pass-filtered crackles
    sf::SoundBuffer synthCollator();   // book binder: low-pass-filtered noise bursts
    sf::SoundBuffer synthFiltered(float seconds, int bursts, float vol); // traveler noise textures
    sf::SoundBuffer buildTeleport();   // dual up/down sweep + shimmer (boss spawn)
    // Gold-disc (power-pellet) bass beat — harmonic, tanh-saturated bass that
    // matches the SpriteKit buildGoldDiscBeat / buildMIBGoldDiscBeat exactly.
    sf::SoundBuffer buildGoldDiscBeat();
    sf::SoundBuffer buildMIBGoldDiscBeat();

    void playBuffer(const sf::SoundBuffer& buf);
    const sf::SoundBuffer& cached(const std::string& key, std::function<sf::SoundBuffer()> build);

    std::unordered_map<std::string, sf::SoundBuffer> cache;
    std::unordered_map<std::string, sf::SoundBuffer> voiceCache;   // loaded from assets/voice/*.wav
    std::unordered_map<std::string, int> voicePoolCounts;          // probed <prefix>_N.wav counts
    int voicePoolCount(const std::string& prefix);
    std::vector<sf::Sound> sounds;
    sf::Sound musicSound;
    sf::Sound bassSound;
    sf::Sound voiceSound;          // dedicated boss-voice channel (never SFX-evicted)
    std::string lastVoiceKey;      // current/last voice clip, to avoid self-restart
    sf::SoundBuffer musicBuffer;
    sf::SoundBuffer bassBuffer;
    bool musicEnabled = false;
    bool bassEnabled = false;
    bool isMIB = false;

    int dotsEatenInCycle = 0;
    bool dotToggle = false;
    float lastDotEatTime = 0;
    sf::Clock dotClock;
    sf::Clock teleportClock;   // guards against overlapping teleport sounds
    bool teleportPlayed = false;
    int sampleRate = 44100;
    std::mt19937 rng{42};
};

} // namespace bm