#pragma once
#include <SFML/Audio.hpp>
#include <vector>
#include <unordered_map>
#include <string>
#include <cmath>
#include <random>
#include <functional>

namespace bm {

class SoundManager {
public:
    SoundManager();
    void playDotBlip();
    void playGoldDisc();
    void playFootstep();
    void playCaptureBoss(int streak);
    void playCaughtByBoss();
    void playFishOrTreat();
    void playTpsDeliver();
    void playGameOver();
    void playLevelStart();
    void playTeleport();
    void playWaterGunPickup();
    void playWaterGunShoot();
    void playWaterGunSplash();
    void playMachine(const std::string& name);
    // Distinct sound for each traveler type when it arrives (idx 0..11, matching
    // the TRAVELERS / SpriteKit TravelerSound order). Mirrors playTravelerArrive.
    void playTravelerArrive(int soundIndex);
    // Plays a pre-rendered digitized voice clip from assets/voice/<key>.wav
    // (generated by scripts/generate_voices.sh). Missing files are silently
    // ignored so the game still runs without the clips.
    void playVoice(const std::string& key);
    // Plays a random clip from a numbered pool: assets/voice/<prefix>_1.wav,
    // <prefix>_2.wav, ... The pool size is probed once (cached), so the line
    // count can change in generate_voices.sh without touching the code.
    void playVoiceRandom(const std::string& prefix);
    void startBackgroundMusic(bool mib);
    void stopBackgroundMusic();
    void startGoldDiscBass(bool mib);
    void stopGoldDiscBass();
    void pauseAudio();
    void resumeAudio();
    // Ducks SFX/music while a boss voice line plays (SpriteKit setDucked). Call
    // once per frame; it polls the voice channel and toggles on start/finish.
    void updateDucking();

private:
    void applyDuck(bool ducked);
    bool voiceDucked = false;

    void playBuffer(const sf::SoundBuffer& buf);
    // Loads (and caches) assets/sfx/<key>.wav via sf::SoundBuffer::loadFromFile.
    // Returns nullptr if the file is missing so the caller stays silent.
    const sf::SoundBuffer* cached(const std::string& key);

    std::unordered_map<std::string, sf::SoundBuffer> cache;
    std::unordered_map<std::string, sf::SoundBuffer> voiceCache;   // loaded from assets/voice/*.wav
    std::unordered_map<std::string, int> voicePoolCounts;          // probed <prefix>_N.wav counts
    int voicePoolCount(const std::string& prefix);
    std::vector<sf::Sound> sounds;
    sf::Sound musicSound;
    sf::Sound bassSound;
    sf::Sound voiceSound;          // dedicated boss-voice channel (never SFX-evicted)
    std::string lastVoiceKey;      // current/last voice clip, to avoid self-restart
    sf::SoundBuffer musicBuffer;
    sf::SoundBuffer bassBuffer;
    bool musicEnabled = false;
    bool bassEnabled = false;
    bool isMIB = false;

    int dotsEatenInCycle = 0;
    bool dotToggle = false;
    float lastDotEatTime = 0;
    sf::Clock dotClock;
    sf::Clock teleportClock;   // guards against overlapping teleport sounds
    bool teleportPlayed = false;
    int sampleRate = 44100;
    std::mt19937 rng{42};
};

} // namespace bm